"""The freshness gate for UNIFIED_INGREDIENT_MAPPING.tsv (#359, #624, #654).

The snapshot is generated by claw from MIM's records and committed here. It went
three weeks and forty PRs stale with every check green, which is what #359 asks
this gate to catch.

The semantics are a drift *budget*, not absolute freshness. Failing on any drift
would red-light every curation PR while the only remedy -- a rebuild needing
three checkouts -- cannot run in CI (#654). So these tests pin both halves: an
ordinary curation batch must pass, and unbounded drift must not.
"""

from __future__ import annotations

import importlib.util
import json
import subprocess
from pathlib import Path

import pytest

_spec = importlib.util.spec_from_file_location(
    "check_unified_freshness",
    Path(__file__).parent.parent / "scripts" / "check_unified_freshness.py",
)
gate = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(gate)


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


@pytest.fixture
def snapshot(tmp_path):
    """A stamped artifact-plus-inputs trio, fresh by construction (no git)."""
    inputs = tmp_path / "data" / "ingredients"
    _write(inputs / "mapped" / "a.yaml", "identifier: CHEBI:1\n")
    _write(inputs / "mapped" / "b.yaml", "identifier: CHEBI:2\n")
    artifact = tmp_path / "u.tsv"
    _write(artifact, "ingredient_name\tmim_id\nNaCl\tCHEBI:26710\n")
    provenance = tmp_path / "u.provenance.json"
    gate.stamp(artifact, provenance, inputs)
    return artifact, provenance, inputs


@pytest.fixture
def git_snapshot(tmp_path):
    """The same, inside a real git repo so drift is measurable."""
    repo = tmp_path / "repo"
    inputs = repo / "data" / "ingredients"
    for name in ("a", "b", "c"):
        _write(inputs / "mapped" / f"{name}.yaml", f"identifier: CHEBI:{name}\n")
    artifact = repo / "u.tsv"
    _write(artifact, "ingredient_name\tmim_id\nNaCl\tCHEBI:26710\n")
    env = {"GIT_AUTHOR_NAME": "t", "GIT_AUTHOR_EMAIL": "t@t", "GIT_COMMITTER_NAME": "t",
           "GIT_COMMITTER_EMAIL": "t@t", "PATH": "/usr/bin:/bin:/usr/local/bin"}
    subprocess.run(["git", "init", "-q"], cwd=repo, check=True, env=env)
    subprocess.run(["git", "add", "-A"], cwd=repo, check=True, env=env)
    subprocess.run(["git", "commit", "-qm", "seed"], cwd=repo, check=True, env=env)
    rev = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=repo,
                         capture_output=True, text=True, check=True, env=env).stdout.strip()
    provenance = repo / "u.provenance.json"
    record = gate.stamp(artifact, provenance, inputs)
    record["mim_rev"] = rev
    provenance.write_text(json.dumps(record, indent=2) + "\n", encoding="utf-8")
    return artifact, provenance, inputs, repo


def test_a_freshly_stamped_snapshot_passes(snapshot):
    assert gate.check(*snapshot) == []


def test_a_hand_edited_artifact_always_fails(snapshot):
    """A generated file edited in place is refused regardless of drift."""
    artifact, provenance, inputs = snapshot
    with artifact.open("a", encoding="utf-8") as handle:
        handle.write("probe\tCHEBI:0\n")
    assert any("has changed since it was stamped" in p for p in gate.check(artifact, provenance, inputs))


def test_a_missing_sidecar_is_stale_not_fresh(snapshot):
    """Absent provenance is the #359 state itself, so it must not pass."""
    artifact, provenance, inputs = snapshot
    provenance.unlink()
    problems = gate.check(artifact, provenance, inputs)
    assert problems and "missing" in problems[0]


def test_a_missing_artifact_is_reported(snapshot):
    artifact, provenance, inputs = snapshot
    artifact.unlink()
    assert gate.check(artifact, provenance, inputs)


def test_unmeasurable_drift_is_advisory_not_failure(snapshot):
    """Outside git the gate cannot count drift, so it must not fail on it (#654)."""
    artifact, provenance, inputs = snapshot
    (inputs / "mapped" / "a.yaml").write_text("identifier: CHEBI:999\n", encoding="utf-8")
    assert gate.check(artifact, provenance, inputs) == []


def test_one_curation_batch_passes(git_snapshot):
    """The #654 scenario: editing a record must not red-light the PR."""
    artifact, provenance, inputs, repo = git_snapshot
    (inputs / "mapped" / "a.yaml").write_text("identifier: CHEBI:999\n", encoding="utf-8")
    assert gate.check(artifact, provenance, inputs, max_drift=25, repo=repo) == []


def test_unbounded_drift_fails(git_snapshot):
    """The #359 scenario: three weeks and forty PRs of drift."""
    artifact, provenance, inputs, repo = git_snapshot
    for name in ("a", "b", "c"):
        (inputs / "mapped" / f"{name}.yaml").write_text(f"identifier: X:{name}\n", encoding="utf-8")
    problems = gate.check(artifact, provenance, inputs, max_drift=2, repo=repo)
    assert problems and "3 record files have changed" in problems[0]


def test_the_budget_boundary_is_inclusive(git_snapshot):
    """Exactly at budget passes; one more does not."""
    artifact, provenance, inputs, repo = git_snapshot
    for name in ("a", "b"):
        (inputs / "mapped" / f"{name}.yaml").write_text(f"identifier: X:{name}\n", encoding="utf-8")
    assert gate.check(artifact, provenance, inputs, max_drift=2, repo=repo) == []
    (inputs / "mapped" / "c.yaml").write_text("identifier: X:c\n", encoding="utf-8")
    assert gate.check(artifact, provenance, inputs, max_drift=2, repo=repo)


def test_a_rename_counts_as_drift(git_snapshot):
    """The #236 scenario; the record count alone would not move."""
    artifact, provenance, inputs, repo = git_snapshot
    (inputs / "mapped" / "b.yaml").rename(inputs / "mapped" / "b_renamed.yaml")
    rev = json.loads(provenance.read_text(encoding="utf-8"))["mim_rev"]
    assert gate.drift_since(rev, inputs, repo) >= 1


def test_the_digest_is_order_independent(tmp_path):
    """Filesystem iteration order must not change the digest."""
    one = tmp_path / "one"; two = tmp_path / "two"
    for name in ("z.yaml", "a.yaml", "m.yaml"):
        _write(one / "mapped" / name, f"identifier: {name}\n")
    for name in ("a.yaml", "m.yaml", "z.yaml"):
        _write(two / "mapped" / name, f"identifier: {name}\n")
    assert gate.inputs_digest(one) == gate.inputs_digest(two)


def test_stamp_records_what_a_reader_needs(snapshot):
    _, provenance, _ = snapshot
    record = json.loads(provenance.read_text(encoding="utf-8"))
    assert set(record) >= {
        "artifact_sha256", "artifact_rows", "mim_inputs_digest",
        "mim_record_count", "stamped_at",
    }


def test_the_committed_snapshot_is_within_budget():
    """Asserted against the real committed artifact."""
    assert gate.check(gate.ARTIFACT, gate.PROVENANCE, gate.INPUTS) == []
