"""The freshness gate for UNIFIED_INGREDIENT_MAPPING.tsv (#359, #624).

The snapshot is generated by claw from MIM's records and committed here. It went
three weeks and forty PRs stale with every check green, and by the time anyone
measured it, it and the SSSOM disagreed about what records are. These tests pin
the property that makes the gate worth having: it must actually go red.
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path

import pytest

_spec = importlib.util.spec_from_file_location(
    "check_unified_freshness",
    Path(__file__).parent.parent / "scripts" / "check_unified_freshness.py",
)
gate = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(gate)

_REPO = Path(__file__).parent.parent


@pytest.fixture
def snapshot(tmp_path):
    """A stamped artifact-plus-inputs trio, fresh by construction."""
    inputs = tmp_path / "ingredients"
    (inputs / "mapped").mkdir(parents=True)
    (inputs / "mapped" / "a.yaml").write_text("identifier: CHEBI:1\n", encoding="utf-8")
    (inputs / "mapped" / "b.yaml").write_text("identifier: CHEBI:2\n", encoding="utf-8")
    artifact = tmp_path / "u.tsv"
    artifact.write_text("ingredient_name\tmim_id\nNaCl\tCHEBI:26710\n", encoding="utf-8")
    provenance = tmp_path / "u.provenance.json"
    gate.stamp(artifact, provenance, inputs)
    return artifact, provenance, inputs


def test_a_freshly_stamped_snapshot_passes(snapshot):
    assert gate.check(*snapshot) == []


def test_a_changed_record_is_caught(snapshot):
    """The #624 scenario: records move, the snapshot does not."""
    artifact, provenance, inputs = snapshot
    (inputs / "mapped" / "a.yaml").write_text("identifier: CHEBI:999\n", encoding="utf-8")
    assert any("data/ingredients has changed" in p for p in gate.check(artifact, provenance, inputs))


def test_an_added_record_is_caught(snapshot):
    artifact, provenance, inputs = snapshot
    (inputs / "mapped" / "c.yaml").write_text("identifier: CHEBI:3\n", encoding="utf-8")
    assert gate.check(artifact, provenance, inputs)


def test_a_removed_record_is_caught(snapshot):
    artifact, provenance, inputs = snapshot
    (inputs / "mapped" / "b.yaml").unlink()
    assert gate.check(artifact, provenance, inputs)


def test_a_rename_is_caught_even_though_the_count_is_unchanged(snapshot):
    """The #236 scenario. A content-only digest would call this fresh."""
    artifact, provenance, inputs = snapshot
    (inputs / "mapped" / "b.yaml").rename(inputs / "mapped" / "b_renamed.yaml")
    problems = gate.check(artifact, provenance, inputs)
    assert problems, "a rename must not be invisible to the gate"
    assert "2 records stamped, 2 now" in problems[0]


def test_a_hand_edited_artifact_is_caught(snapshot):
    """The file is generated; editing it in place is the thing to refuse."""
    artifact, provenance, inputs = snapshot
    with artifact.open("a", encoding="utf-8") as handle:
        handle.write("probe\tCHEBI:0\n")
    assert any("has changed since it was stamped" in p for p in gate.check(artifact, provenance, inputs))


def test_a_missing_sidecar_is_stale_not_fresh(snapshot):
    """Absent provenance is the #359 state itself, so it must not pass."""
    artifact, provenance, inputs = snapshot
    provenance.unlink()
    problems = gate.check(artifact, provenance, inputs)
    assert problems and "missing" in problems[0]


def test_a_missing_artifact_is_reported(snapshot):
    artifact, provenance, inputs = snapshot
    artifact.unlink()
    assert gate.check(artifact, provenance, inputs)


def test_the_digest_is_order_independent(tmp_path):
    """Filesystem iteration order must not change the digest."""
    one = tmp_path / "one"; (one / "mapped").mkdir(parents=True)
    two = tmp_path / "two"; (two / "mapped").mkdir(parents=True)
    for name in ("z.yaml", "a.yaml", "m.yaml"):
        (one / "mapped" / name).write_text(f"identifier: {name}\n", encoding="utf-8")
    for name in ("a.yaml", "m.yaml", "z.yaml"):
        (two / "mapped" / name).write_text(f"identifier: {name}\n", encoding="utf-8")
    assert gate.inputs_digest(one) == gate.inputs_digest(two)


def test_stamp_records_what_a_reader_needs(snapshot):
    _, provenance, _ = snapshot
    record = json.loads(provenance.read_text(encoding="utf-8"))
    assert set(record) >= {
        "artifact_sha256", "artifact_rows", "mim_inputs_digest",
        "mim_record_count", "stamped_at",
    }


def test_the_committed_snapshot_is_current():
    """The gate's whole point, asserted against the real committed artifact."""
    assert gate.check(gate.ARTIFACT, gate.PROVENANCE, gate.INPUTS) == []
