#!/usr/bin/env python3
"""Extract roles for top 100 ingredients from CultureMech analysis.

This script reads the top100_role_crossref.yaml generated by analyze_culturemech_roles.py
and adds structured role assignments with CultureMech DATABASE_ENTRY citations.

Input: data/analysis/top100_role_crossref.yaml
Output: Updated data/curated/mapped_ingredients.yaml
"""

import re
import sys
from pathlib import Path

import yaml

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from mediaingredientmech.curation.ingredient_curator import IngredientCurator
from mediaingredientmech.utils.role_facets import add_role
from mediaingredientmech.utils.role_iteration import FACET_ROLE_SLOTS, iter_role_assignments

# The crossref input was generated against the retired flat IngredientRoleEnum,
# so two of its values need resolving before they can be written to a facet:
#   * SALT is dropped — upstream it tags water, HCl, ethanol and DMSO, so it
#     carries no usable meaning.
#   * MINERAL is resolved to the element source the ingredient actually supplies,
#     matched on the ingredient name (the facets have no generic mineral role).
_IRON = re.compile(r"(^Fe|ferric|ferrous|iron)", re.I)
_TRACE_METAL = re.compile(
    r"(MoO4|molybd|WO4|tungst|SeO3|SeO4|selen|^CoCl|^CoSO|cobalt|^Cu|copper|"
    r"^NiCl|^NiSO|nickel|^Zn|zinc|^Mn|mangan|H3BO3|boric|borate|vanad)",
    re.I,
)
_SULFUR = re.compile(r"(^sulfur$|^S8$|H2SO4|sulfuric|^Na2S\b|sodium sulfide)", re.I)
_PHOSPHATE = re.compile(r"(phosphat|PO4)", re.I)


def resolve_role(role_enum: str, preferred_term: str) -> str | None:
    """Map a crossref role value onto a facet role, or None to drop it.

    Args:
        role_enum: Role value from the crossref file
        preferred_term: Ingredient name, used to pick the element source for MINERAL

    Returns:
        Facet role name, or None if the value should not be written
    """
    if role_enum == "SALT":
        return None
    if role_enum != "MINERAL":
        return role_enum
    if _IRON.search(preferred_term):
        return "IRON_SOURCE"
    if _TRACE_METAL.search(preferred_term):
        return "TRACE_ELEMENT"
    if _SULFUR.search(preferred_term):
        return "SULFUR_SOURCE"
    if _PHOSPHATE.search(preferred_term):
        return "PHOSPHATE_SOURCE"
    return "MINERAL_SOURCE"


def load_top100_crossref(crossref_path: Path) -> dict:
    """Load top 100 cross-reference data.

    Args:
        crossref_path: Path to top100_role_crossref.yaml

    Returns:
        Dictionary with top 100 ingredient data
    """
    with open(crossref_path) as f:
        return yaml.safe_load(f)


def ingredient_has_role(record: dict, role_enum: str) -> bool:
    """Check if ingredient already has a specific role.

    Args:
        record: Ingredient record
        role_enum: Facet role value (e.g., "TRACE_ELEMENT")

    Returns:
        True if role already assigned
    """
    for _slot, role_assignment in iter_role_assignments(record, slots=FACET_ROLE_SLOTS):
        if role_assignment.get("role") == role_enum:
            return True
    return False


def format_occurrence_summary(occurrence_count: int, role_enum: str) -> str:
    """Format occurrence summary for curator note.

    Args:
        occurrence_count: Total occurrence count
        role_enum: Role enum value

    Returns:
        Formatted summary string
    """
    role_display = role_enum.replace("_", " ").title()
    return f"High-confidence assignment. Appears in {occurrence_count} media occurrences as '{role_display}'."


def extract_roles_for_top100(
    curator: IngredientCurator,
    crossref_data: dict,
    dry_run: bool = False,
) -> tuple[int, int, int]:
    """Extract and add roles for top 100 ingredients.

    Args:
        curator: IngredientCurator instance
        crossref_data: Top 100 cross-reference data
        dry_run: If True, preview changes without saving

    Returns:
        Tuple of (ingredients_updated, roles_added, roles_skipped)
    """
    ingredients_updated = 0
    roles_added = 0
    roles_skipped = 0

    # Build lookup by ingredient ID
    ingredient_lookup = {record["id"]: record for record in curator.records}

    print(f"\nProcessing {len(crossref_data['ingredients'])} ingredients from crossref...")

    for i, ingredient_data in enumerate(crossref_data["ingredients"], 1):
        ingredient_id = ingredient_data["id"]
        preferred_term = ingredient_data["preferred_term"]
        occurrence_count = ingredient_data["occurrence_count"]
        confidence = ingredient_data["confidence"]
        all_roles = ingredient_data["all_roles"]

        # Get unique roles (all_roles may have duplicates from multiple annotations)
        unique_roles = sorted(set(all_roles))

        if i % 25 == 0:
            print(f"  Processed {i}/{len(crossref_data['ingredients'])} ingredients...")

        # Find record in curator
        record = ingredient_lookup.get(ingredient_id)
        if not record:
            print(f"⚠️  Ingredient {ingredient_id} ({preferred_term}) not found in curator records")
            continue

        # Track if this ingredient was updated
        ingredient_updated = False

        # Add each unique role
        for crossref_role in unique_roles:
            role_enum = resolve_role(crossref_role, preferred_term)
            if role_enum is None:
                roles_skipped += 1
                continue

            # Skip if role already exists
            if ingredient_has_role(record, role_enum):
                roles_skipped += 1
                continue

            # Get role-specific annotations
            role_annotations = [
                ann
                for ann in ingredient_data["raw_annotations"]
                if ann["role_enum"] == crossref_role
            ]

            # Build excerpt from first annotation
            if role_annotations:
                first_ann = role_annotations[0]
                role_text = first_ann["role_text"]
                properties = ", ".join(first_ann["properties"])
                excerpt = f"Role: {role_text}; Properties: {properties}"
            else:
                excerpt = f"Role: {role_enum}"

            # Format curator note
            curator_note = format_occurrence_summary(occurrence_count, role_enum)

            if dry_run:
                print(
                    f"  [DRY RUN] Would add {role_enum} to {ingredient_id} ({preferred_term}), conf={confidence:.2f}"
                )
            else:
                # Add role using curator
                add_role(
                    curator,
                    record,
                    role_enum,
                    confidence=confidence,
                    reference_text=f"CultureMech database ({occurrence_count} occurrences in media formulations)",
                    reference_type="DATABASE_ENTRY",
                    url="https://github.com/CultureBotAI/CultureMech",
                    excerpt=excerpt,
                    curator_note=curator_note,
                )

            roles_added += 1
            ingredient_updated = True

        if ingredient_updated:
            ingredients_updated += 1

    return ingredients_updated, roles_added, roles_skipped


def main():
    """Main extraction workflow."""
    import argparse

    parser = argparse.ArgumentParser(
        description="Extract roles for top 100 ingredients from CultureMech analysis"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview changes without saving",
    )
    parser.add_argument(
        "--crossref",
        type=Path,
        default=Path("data/analysis/top100_role_crossref.yaml"),
        help="Path to top100_role_crossref.yaml",
    )
    args = parser.parse_args()

    print("=" * 80)
    print("Extract Roles for Top 100 Ingredients")
    print("=" * 80)

    if args.dry_run:
        print("\n⚠️  DRY RUN MODE - No changes will be saved\n")

    # Load cross-reference data
    print(f"\nLoading cross-reference from: {args.crossref}")
    crossref_data = load_top100_crossref(args.crossref)
    print(f"Loaded {len(crossref_data['ingredients'])} ingredients")
    print(f"Average confidence: {crossref_data['average_confidence']:.3f}")

    # Load mapped ingredients
    data_path = Path("data/curated/mapped_ingredients.yaml")
    curator = IngredientCurator(
        data_path=data_path, curator_name="extract_top100_roles"
    )

    print(f"\nLoading ingredient records from: {data_path}")
    curator.load()
    print(f"Loaded {len(curator.records)} records")

    # Extract roles
    ingredients_updated, roles_added, roles_skipped = extract_roles_for_top100(
        curator, crossref_data, dry_run=args.dry_run
    )

    # Save results
    if not args.dry_run:
        print("\nSaving updated records...")
        curator.save()
        print(f"✅ Saved to {data_path}")
    else:
        print("\n⚠️  DRY RUN - No changes saved")

    # Summary statistics
    print("\n" + "=" * 80)
    print("EXTRACTION SUMMARY")
    print("=" * 80)
    print(f"Ingredients processed: {len(crossref_data['ingredients'])}")
    print(f"Ingredients updated: {ingredients_updated}")
    print(f"Roles added: {roles_added}")
    print(f"Roles skipped (already exist or dropped): {roles_skipped}")

    if roles_added > 0:
        avg_roles = roles_added / ingredients_updated if ingredients_updated > 0 else 0
        print(f"Average roles per ingredient: {avg_roles:.2f}")

    if not args.dry_run:
        print("\n✅ Top 100 role extraction complete!")
    else:
        print("\n✅ Dry run complete! Re-run without --dry-run to apply changes.")


if __name__ == "__main__":
    main()
